<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>EntraDpapiDecryptCS</RootNamespace>
    <AssemblyName>EntraDpapiDecrypt</AssemblyName>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
